### ISSUE TITLE
Combinable overlays

### ISSUE THREAD

**Issue by AllayBreeze** [GeorgeV220/SkinOverlay#67]
**Is your feature request related to a problem? Please describe.**
Currently players can only wear one overlay that each time, but cannot wear two or more. For example, the mustache and alley cannot be worn together; or if I make a "pirate hat" overlay splitted from the pirate set, and a "policeman uniform" from the policeman set, because these are two independent overlays, I cannot make myself wearing a pirate hat and a policeman uniform at the same time.
It'll be great if multiple overlays can be worn together. With this, not only can we make single clothing overlays, like hat, shirt, pants or shoes and combine them according to our favors, but also we can wear multiple layers of clothings at the same time, like shirt+coat+cloak.

**Describe the solution you'd like**
Add two new arguments to "overlays" configuration: **type** and **layer**.
"type" is a string that can be freely defined, used to define the kind of an overlay.
"layer" is an integer that defines if this overlay's texture should override anothers.
If there're two different layers that have the same "type" and "layer" value, these two layers will not be able to wear together.
An example to further explain these two arguments:
```
  overlays:
    pirate_hat:
      type: HEAD
      layer: 1
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    pirate_coat:
      type: BODY
      layer: 1
      hat: true
      right_sleeve: false
      left_sleeve: false
      jacket: false
      right_pants: true
      left_pants: true
      cape: true
    mustache:
      type: HEAD
      layer: 2
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
    policeman_cap:
      type: HEAD
      layer: 1
      hat: true
      right_sleeve: true
      left_sleeve: true
      jacket: true
      right_pants: true
      left_pants: true
      cape: true
```
In this example, pirate hat can be weared with pirate coat or mustache together, but cannot with policeman cap together due to the samenesses of their type and layer; and if wear pirate hat and mustache together, the texture of mustache will override pirate hat's.

**Describe alternatives you've considered**

**Additional context**
The /skinoverlay clear command can add an argument to decide which overlay should be removed.
